platform :ios, '15.0'
use_frameworks!

target 'ChatLayout_Example' do
  pod 'ChatLayout', :path => '../'
  pod 'InputBarAccessoryView'
  pod 'DifferenceKit'
  # pod 'RecyclerView'
  pod 'RecyclerView', :path => '../../RecyclerView/RecyclerView.podspec'
  pod 'FPSCounter', '~> 4.0'
  pod 'InterposeKit', :git => 'https://github.com/steipete/InterposeKit'

  target 'ChatLayout_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end