platform :ios, '12.0'
use_frameworks!

target 'ChatLayout_Example' do
  pod 'ChatLayout', :path => '../'
  pod 'InputBarAccessoryView'
  pod 'DifferenceKit'
  pod 'FPSCounter', '~> 4.0'

  target 'ChatLayout_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end