podspec: ChatLayout.podspec
clean: true
author: Evgeny Kazaev
author_url: https://github.com/ekazaev
output: docs
documentation: ./*.md
theme: fullwidth

custom_categories:
  - name: Core
    children:
      - CollectionViewChatLayout
      - ChatLayoutDelegate
      - ChatLayoutAttributes
      - ChatLayoutSettings
      - ChatLayoutPositionSnapshot
      - ChatLayoutInvalidationContext
      - ItemKind
      - ItemSize
      - ChatItemAlignment
      - ChatItemPinningType
      - InitialAttributesRequestType

  - name: Extras
    children:
      - ContainerCollectionViewCell
      - ContainerCollectionViewCellDelegate
      - ContainerCollectionReusableView
      - MessageContainerView
      - CellLayoutContainerView
      - CellLayoutContainerViewAlignment
      - EdgeAligningView
      - SwappingContainerView
      - ImageMaskedView
      - ImageMaskedViewTransformation
      - RoundedCornersContainerView
      - StaticViewFactory
      - VoidViewFactory
